### ISSUE TITLE
add pika v1.0.0b1

### ISSUE THREAD

**Issue by ltalirz** [conda-forge/pika-feedstock#9]
Hi!

pika has recently released a v1.0.0b1, see https://pypi.org/project/pika/1.0.0b1/

Would you mind making this available here at conda forge?
We are missing this dependency in some of our projects and this would really help us out.

**Comment by frol** [comment]
@jakirkham is there an infrastructure for beta/backport releases?

**Comment by ltalirz** [comment]
Would you like me to provide a PR?

**Comment by frol** [comment]
Please, go ahead!

1. Create a PR against `dev` branch.
2. Create `recipe/conda_build_config.yaml` file with the following content:

    ```yaml
    channel_targets:
    - conda-forge dev
    ```

**Comment by ltalirz** [comment]
Done :-) #10

**Comment by ltalirz** [comment]
@frol Sorry to bother again about this, but now that it's merged, how do I search for this package?

It does not show up in the output of `conda search -c conda-forge pika` 

Also, looking a bit into this, is
```yml
channel_targets:
- conda-forge dev
```
correct or should it have been
```yml
channel_targets:
- conda-forge
- dev
```
? Or maybe
```yml
channel_targets:
- [conda-forge, dev]
```
?

**Comment by ltalirz** [comment]
I see that [the build of the `dev` branch failed](https://circleci.com/gh/conda-forge/pika-feedstock/32?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
Perhaps restarting the CI would already fix the problem?

**Comment by frol** [comment]
The failure is with CircleCI infrastructure, so I reran the build.

The syntax is correct as far as I can tell. I just followed the process from: https://github.com/conda-forge/apispec-feedstock/pull/22

**Comment by ltalirz** [comment]
Thanks, that did the trick
```
$ conda search -c conda-forge/label/dev pika
Loading channels: done
# Name                  Version           Build  Channel
pika                    1.0.0b1            py_0  conda-forge/label/dev
```

**Comment by ltalirz** [comment]
@frol Unfortunately, there is currently a problem on conda-forge that the policy of how to *depend* on dev-packages has not yet been figured out definitively.
Currently, new PRs to staged recipes can't depend on them.
As discussed in https://github.com/conda-forge/staged-recipes/pull/6893#issuecomment-434514551, some people just merge the (failing) PR and then refactor the feedstock using `conda smithy rerender`.

It's obviously not ideal, though, and in my [PR for topika](https://github.com/conda-forge/staged-recipes/pull/6948) I've been advised to rather put pika 1.0.0b1 into the main conda channel.
Would you be happy to do that?

**Comment by frol** [comment]
To be honest, I don’t care much about feedstocks anymore. Would you like to become a maintainer for this feedstock?

**Comment by ltalirz** [comment]
@frol  sure, no problem!
